package com.github.yuriisurzhykov.kevent.events.persisted.core.database

/**
 * The `AutoGeneratedDatabase` interface represents a database that is auto-generated.
 * It is just a marker for `RoomDatabase`, that intended to include auto-generated entities
 * and DAOs.
 * It provides functionality for interacting with the database and performing operations
 * such as event registration.
 */
interface AutoGeneratedDatabase
