package com.github.yuriisurzhykov.kevent.events.persisted.core.database

import kotlin.reflect.KClass

/**
 * Annotation class used to specify an automatic migration between two versions of a database.
 * Should be used for [AutoDatabase] annotation and [AutoGeneratedDatabase] classes only.
 *
 * @property from   The starting version of the database.
 * @property to     The ending version of the database.
 * @property spec   The specific [kotlin.reflect.KClass] of the migration, defaults to [kotlin.Any].
 */
annotation class AutoMigration(
    val from: Int,
    val to: Int,
    val spec: KClass<*> = Any::class
)
